### ISSUE TITLE
Updates for Parcel

### ISSUE THREAD

**Issue by devongovett** [GoogleChromeLabs/tooling.report#357]
Hey all. Congrats on your launch! 🥳 

There are many tests on the site that Parcel fails or receives a partial pass for due to missing documentation, as it's the only pre-release tool on the site. You may have missed it, but as of the beta release a few weeks ago, we have a new docs website: https://v2.parceljs.org/. It still very much a work in progress, but it already covers many of the things you mention as lacking documentation, so I thought I'd file an issue to point you there.

Here are the tests I believe Parcel should pass given the new docs, along with a few that may have been fixed since the test was last performed.

* [Import a binary file as an asset URL](https://bundlers.tooling.report/non-js-resources/binary/url/)
  * Possible using the `url:` named pipeline. [See docs](https://v2.parceljs.org/configuration/plugin-configuration/#predefined-(offical)-named-pipelines).
* [Can CSS be imported as a JavaScript string?](https://bundlers.tooling.report/non-js-resources/css/source/)
  * Use the `bundle-text:` named pipeline. [See docs](https://v2.parceljs.org/configuration/plugin-configuration/#predefined-(offical)-named-pipelines).
* [Can CSS be imported to produce a stylesheet URL?](https://bundlers.tooling.report/non-js-resources/css/url/)
  * Use the `url:` named pipeline. [See docs](https://v2.parceljs.org/configuration/plugin-configuration/#predefined-(offical)-named-pipelines).
* [Can CSS "Modules" be used for scoping?](https://bundlers.tooling.report/non-js-resources/css/module/)
  * [See docs](https://v2.parceljs.org/languages/postcss/#css-modules). Not sure why you'd import a CSS module into an HTML file, nor how that would work. It's not something that appears to be tested against other tools.
* [Import custom file types from JavaScript](https://bundlers.tooling.report/non-js-resources/custom/)
  * Use a custom named pipeline. [See docs](https://v2.parceljs.org/configuration/plugin-configuration/#named-pipelines).
* [Can images be imported as data URLs?](https://bundlers.tooling.report/non-js-resources/image/data-url/)
  * Use the `data-url:` named pipeline. See [docs](https://v2.parceljs.org/configuration/plugin-configuration/#predefined-(offical)-named-pipelines).
* [Can URL hashing be selectively disabled?](https://bundlers.tooling.report/hashing/avoid-hash/)
  * This can be accomplished using a custom Namer plugin to exclude the `hashReference` when needed. See [docs](https://v2.parceljs.org/plugin-system/namer/).
* [Can a map be used to centralized bundle hashes?](https://bundlers.tooling.report/hashing/avoid-cascade/)
  * This happens by default. A manifest is inserted into the entry JS bundles, and is used to generate URLs to both other JS bundles and other assets referenced from JS at runtime.
* [Can processed scripts be inlined into HTML?](https://bundlers.tooling.report/non-js-resources/html/inlining-scripts/)
  * This could be accomplished by using an inline script in HTML, with an import. `<script>import '...';</script>`.
* [Import a binary file as an array buffer](https://bundlers.tooling.report/non-js-resources/binary/arraybuffer/)
  * This can be done with `fs.readFileSync` just like in the Browserify test. [See docs](https://v2.parceljs.org/features/node-emulation/#📄-inlining-fs.readfilesync). Alternatively, if you need to process the file through all the plugins first rather than just requiring the raw file, you could use the `data-url:` pipeline like you already have in the test. [See docs](https://v2.parceljs.org/configuration/plugin-configuration/#predefined-(offical)-named-pipelines).

**Comment by surma** [comment]
Thanks @devongovett and congrats on _your_ launch as well, then :tada: 

I’m on vacation for the next 2 weeks, but I'll update everything once I’m back. Super excited to dive in! Thanks for doing half the work for me already.

**Comment by jakearchibald** [comment]
I'll be able to pick up some/all of this in the meantime. Looking forward
to digging into it!

If it provides a big score jump, we'll make some noise around that too.

**Comment by jakearchibald** [comment]
Also, wow, thanks for highlighting the individual tests too!

**Comment by jakearchibald** [comment]
* [x] [Import a binary file as an asset URL](https://bundlers.tooling.report/non-js-resources/binary/url/)
  * Now passes!
* [x] [Can CSS be imported as a JavaScript string?](https://bundlers.tooling.report/non-js-resources/css/source/)
  * A partial pass due to https://github.com/parcel-bundler/parcel/issues/4855
* [x] [Can CSS be imported to produce a stylesheet URL?](https://bundlers.tooling.report/non-js-resources/css/url/)
  * A fail due to https://github.com/parcel-bundler/parcel/issues/4856 
* [x] [Can CSS "Modules" be used for scoping?](https://bundlers.tooling.report/non-js-resources/css/module/)
  * Now passes!
* [x] [Import custom file types from JavaScript](https://bundlers.tooling.report/non-js-resources/custom/)
  * No change: This test requires writing a plugin, but I don't think the docs are complete enough yet. @devongovett if the consensus is that the docs _are_ ready, I can create an issue detailing where I hit difficulties trying to figure out how I'd write this. LMK.
* [x] [Can images be imported as data URLs?](https://bundlers.tooling.report/non-js-resources/image/data-url/)
  * Now passes!
* [x] [Can URL hashing be selectively disabled?](https://bundlers.tooling.report/hashing/avoid-hash/)
  * Stays the same until [for now](https://github.com/parcel-bundler/parcel/issues/4553#issuecomment-656689896). Actually, I think this should be a fail rather than a pass, but I'll leave it for now.
* [x] [Can a map be used to centralized bundle hashes?](https://bundlers.tooling.report/hashing/avoid-cascade/)
  * Now passes!
* [x] [Can processed scripts be inlined into HTML?](https://bundlers.tooling.report/non-js-resources/html/inlining-scripts/)
  * A partial pass due to a lack of documentation and bugs
* [x] [Import a binary file as an array buffer](https://bundlers.tooling.report/non-js-resources/binary/arraybuffer/)
  * I'm going to keep this as a partial pass because the Buffer polyfill is pretty heavy.

**Comment by mischnic** [comment]
>  Import custom file types from JavaScript

Looks like Devon missed the `transform files at build time to "wrap" them` part. The docs for most plugin types (in this case, a transformer) aren't ready yet.

**Comment by jakearchibald** [comment]
@mischnic no problem. Let us know when you reckon they're ready. One of us will 'test' them and give feedback on whatever we can't figure out.

**Comment by jakearchibald** [comment]
@mischnic @devongovett 

> * [Can processed scripts be inlined into HTML?](https://bundlers.tooling.report/non-js-resources/html/inlining-scripts/)
>   * This could be accomplished by using an inline script in HTML, with an import. `<script>import '...';</script>`.

Is this behaviour documented anywhere?

Filed https://github.com/parcel-bundler/website/issues/629

**Comment by jakearchibald** [comment]
@mischnic @devongovett https://github.com/GoogleChromeLabs/tooling.report/pull/372 - let me know if I've gotten anything wrong here
